#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in solid
do
   rm -f 0*/$i/{nut,alphat,epsilon,k,U,p_rgh}
done


for i in flame solid
do
   runApplication -s $i changeDictionary -region $i
done


#-- Run on single processor
runApplication `getApplication`

# Decompose
#runApplication decomposePar -allRegions

# Run
#runParallel `getApplication`

# Reconstruct
#runApplication reconstructPar -allRegions


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

echo
echo "Converting output to VTK..."
echo
for i in flame solid
do
	foamToVTK -region $i
done
#------------------------------------------------------------------------------
